# Generated by Django 4.1.6 on 2023-02-09 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debug', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('api_name', models.TextField(max_length=255)),
                ('data_type', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('help_text', models.TextField(blank=True, null=True)),
                ('formula', models.TextField(blank=True, null=True)),
                ('attributes', models.CharField(blank=True, max_length=255)),
                ('field_usage_display', models.TextField(blank=True, null=True)),
                ('field_usage_display_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('finished_date', models.DateTimeField(blank=True, null=True)),
                ('org_id', models.CharField(max_length=255)),
                ('org_name', models.CharField(blank=True, max_length=255)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('access_token', models.CharField(blank=True, max_length=255)),
                ('instance_url', models.CharField(blank=True, max_length=255)),
                ('include_field_usage', models.BooleanField(default=False)),
                ('include_managed_objects', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('error', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='StandardObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('api_name', models.CharField(max_length=255)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getschema.schema')),
            ],
        ),
        migrations.CreateModel(
            name='FieldUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Apex Class', 'Apex Class'), ('Apex Trigger', 'Apex Trigger'), ('Email Template', 'Email Template'), ('Field Update', 'Field Update'), ('Page Layout', 'Page Layout'), ('Flow', 'Flow'), ('Outbound Message', 'Outbound Message'), ('VisualForce Component', 'VisualForce Component'), ('VisualForce Page', 'VisualForce Page'), ('Workflow', 'Workflow')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getschema.field')),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getschema.object'),
        ),
    ]
