# Generated by Django 6.0.1 on 2026-01-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getschema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='status',
            field=models.CharField(blank=True, default='Not Started', max_length=255),
        ),
    ]
